_base:
  - ${luolib.conf_root:}/aug/2D.yaml
  - optimizer: ${luolib.conf_root:}/optimizer/adamw.yaml

train_cache_num: 200
dataloader_num_workers: 12
train_batch_size: 64
gradient_clip_val: 1
gradient_clip_algorithm: norm
max_epochs: null
val_check_interval: 25
save_top_k: 1
dummy_dim: 2
pool_types:
  - ST
  - AT
#  - CT
pooling_layer: max
precision: 32
backbone:
  key_prefix: backbone.
  kwargs:
    use_checkpoint: true
use_post: false
