_base:
  - ${luolib.conf_root:}/aug/2D.yaml
  - optimizer: ${luolib.conf_root:}/optimizer/adamw.yaml

train_cache_num: 200
dataloader_num_workers: 8
train_batch_size: 16
gradient_clip_val: 1
gradient_clip_algorithm: norm
max_epochs: null
val_check_interval: 25
save_top_k: 1
dummy_dim: 2
pool_types:
  - ST
  - AT
#  - CT
pooling_layer: avg
precision: 32
backbone:
  key_prefix: backbone.

#scheduler:
#  name: plateau
#  interval: step
#  frequency: ${val_check_interval}
#  reduce_on_plateau: true
#  kwargs:
#    decay_rate: 0.2
#    patience_t: 10
#    mode: min

rotate_p: 0.5
scale_p: 0.5
gaussian_noise_p: 0
gaussian_smooth_p: 0
scale_intensity_p: 0
shift_intensity_p: 0
adjust_contrast_p: 0
simulate_low_res_p: 0
# gamma_p: 0
