_base:
  - _default.yaml
  - backbone: ../../../model/backbone/swin-b-3l.yaml
    scheduler: ${luolib.conf_root:}/scheduler/_step.yaml

backbone:
  kwargs:
    drop_path_rate: 0.2
pooling_level_stride: [16, 16, 2]
pooling_th: 52
sample_shape: [256, 192, 16]
max_steps: 1000
backbone_optim:
  lr: 1e-5
  weight_decay: 0
optimizer:
  lr: 5e-5
scheduler:
  name: multistep
  kwargs:
    warmup_t: 100
    decay_t: [400, 700]
    decay_rate: 0.1

pretrain_cv_dir: output/seg/base/run-42
