num_stages: 6
z_strides: [1, 1, 1, 2, 2]
swin_window_size: [6, 6, 6]
vit_depths: [2, 2, 6, 2]
vit_num_heads: [3, 6, 12, 24]
base_feature_size: 12
sample_size: 192
sample_slices: 24
input_modalities:
  - T2
spacing: [0.46875, 0.46875, -1]
learning_rate: 4e-5
num_crop_samples: 4
train_batch_size: 4
num_train_epochs: 250
warmup_epochs: 10
num_seg_heads: 3
flip_p: 0.5
rotate_p: 0.5
dice_include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
crop_pos: 3
squared_dice: false
