_base:
  - _default.yaml
  - scheduler: ${luolib.conf_root:}/scheduler/_step.yaml

do_train: true
max_steps: 500
backbone_optim:
  lr: 2e-6
  weight_decay: 0
optimizer:
  lr: 1e-5
scheduler:
  name: multistep
  frequency: 100
  kwargs:
    warmup_t: 0
    decay_t: [400]
    decay_rate: 0.2
