channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - notebook
  - omegaconf
  - numpy
  - scikit-learn
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision
  - einops
  - pytorch-lightning
  - torchmetrics
  - transformers
  - timm
  - wandb
  - libprotobuf=3  # https://github.com/wandb/wandb/issues/5633
  - llvm-openmp<16  # https://github.com/pytorch/pytorch/issues/99625
  - pandas
  - openpyxl
  - seaborn
  - nibabel
  - pydicom
  - nipype

  - pip
  - pip:
    - pyradiomics
    - xgboost
    - cytoolz
    - antspyx
    - openmim # mim install mmcv, pip install mmsegmentation
    - -e third-party/MONAI
