dependencies:
  - defaults::conda=4.10.3
  - defaults::python=3.9.7
  - conda-forge::tqdm=4.62.3

  - pytorch::pytorch=1.10.0
  - pytorch::torchvision=0.11.1
  - nvidia::cudatoolkit=11.3

  - conda-forge::numpy=1.21.3
  - conda-forge::scikit-learn=1.0
  - conda-forge::pandas=1.3.4
  - conda-forge::openpyxl=3.0.9
  - conda-forge::matplotlib=3.4.3

  - conda-forge::pydicom=2.2.2
  - conda-forge::nibabel=3.2.1

  - conda-forge::pip=21.3
  - pip:
    - mashumaro==2.8
    - monai-weekly
    - itk
