channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - ruamel.yaml=0.17.21
  - aenum==3.1.11
  - numpy=1.23.3
  - einops=0.4.1
  - pytorch::pytorch=1.12.1
  - cudatoolkit=11.6
  - pytorch::torchvision=0.13.1
  - pytorch-lightning=1.7.7
  - lightning-bolts=0.5.0
  - torchmetrics=0.10.0
  - transformers==4.22.2
  - wandb==0.13.4
  - scikit-learn=1.1.2
  - pandas=1.5.0
  - openpyxl=3.0.10
#  - tabulate=0.8.10
  - matplotlib=3.6.0
  - nibabel=4.0.2

  - pydicom=2.3.0
  - fslpy=3.10.0
  # work around for: https://github.com/SimpleITK/SimpleITK/issues/1433, waiting for ITK 5.3
  - SimpleITK::SimpleITK=2.0.2

  - pip=22.2.2
  - pip:
    - pyradiomics==3.0.1
#    - itk==5.2.1.post1
    - git+https://github.com/FabianIsensee/hiddenlayer.git@more_plotted_details#egg=hiddenlayer
    - -e third-party/MONAI
    - -e third-party/HD-BET
    - -e third-party/nnUNet
