channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - notebook
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.8
  - timm
  - pytorch-lightning
  - torchmetrics
  - einops
  - transformers
  - wandb
  - scikit-learn
  - pandas
  - openpyxl
  - seaborn
  - nibabel
  - pydicom
  - fslpy

  - pip
  - pip:
    - pyradiomics
    - xgboost
    - -e third-party/MONAI
