channels:
  - conda-forge
dependencies:
  - python=3.9
  - tqdm=4.62.3
  - ruamel.yaml=0.17.19

  - pytorch::pytorch=1.10.1
  - defaults::cudatoolkit=11.3
  - pytorch::torchvision=0.11.2
  - pytorch::ignite=0.4.7
  - pytorch-lightning=1.5.8
  - tensorboard=2.7.0
  - transformers=4.15.0

  - numpy=1.22.0
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - openpyxl=3.0.9
  - tabulate=0.8.9
  - matplotlib=3.5.1

  - pydicom=2.2.2
  - nibabel=3.2.1
  # work around for: https://github.com/SimpleITK/SimpleITK/issues/1433, waiting for ITK 5.3
  - SimpleITK::SimpleITK=2.0.2

  - pip=21.3.1
  - pip:
    - pyradiomics==3.0.1
    - aenum==3.1.5
    - itk==5.2.1.post1
    - git+https://github.com/FabianIsensee/hiddenlayer.git@more_plotted_details#egg=hiddenlayer
    - -e third-party/MONAI
    - -e third-party/HD-BET
    - -e third-party/nnUNet
