channels:
  - conda-forge
dependencies:
  - python=3.11 # https://github.com/AIM-Harvard/pyradiomics/issues/886
  - notebook
  - numpy
  - cupy
  - pytorch=2.5
  - torchvision
  - einops
  - lightning
  - torchmetrics
  - transformers
  - xformers
  - timm
  - wandb
  - pandas
  - openpyxl
  - xlsxwriter
  - scikit-learn
  - xgboost
  - r-base
  - statsmodels
  - seaborn
  - monai
  - simpleitk
#  - nibabel
#  - pydicom
  - nipype
  - zstandard
  - cytoolz
  - jsonargparse  # for lightning CLI
  - dcm2niix

  - pip
  - pip:
    - antspyx
    - python-gdcm
    - jsonargparse[signatures, omegaconf]  # only for extras
    - pyradiomics
#    - -e third-party/nnUNet
#    - git+https://github.com/FabianIsensee/hiddenlayer.git
    - rpy2
channel_priority: strict
