channels:
  - conda-forge
dependencies:
  - python=3.11 # https://github.com/AIM-Harvard/pyradiomics/issues/886
  - notebook
  - numpy
  - cupy
  - pytorch=2.5
  - torchvision
  - einops
  - lightning
  - torchmetrics
  - transformers
  - xformers
  - timm
  - wandb
  - pandas
  - openpyxl
  - scikit-learn
  - xgboost
  - r-base
  - statsmodels
  - seaborn
  - nibabel
  - pydicom
  - nipype
  - zstandard
  - cytoolz

  - pip
  - pip:
    - pyradiomics
    - antspyx
    - jsonargparse[signatures, omegaconf]  # for lightning CLI
    - -e third-party/nnUNet
    - git+https://github.com/FabianIsensee/hiddenlayer.git
    - rpy2
channel_priority: strict
