channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - tqdm=4.64.0
  - ruamel.yaml=0.17.21
  - aenum==3.1.11

  - pytorch::pytorch=1.12.0
  - cudatoolkit=11.6
  - pytorch::torchvision=0.13.0
  - pytorch-lightning=1.6.4
  - wandb==0.12.20
  - transformers==4.20.1

  - numpy=1.23.0
  - scikit-learn=1.1.1
  - pandas=1.4.3
  - openpyxl=3.0.9
  - tabulate=0.8.10
  - matplotlib=3.5.2

  - pydicom=2.3.0
  - nibabel=4.0.1
  - fslpy=3.10.0
  # work around for: https://github.com/SimpleITK/SimpleITK/issues/1433, waiting for ITK 5.3
  - SimpleITK::SimpleITK=2.0.2

  - pip=22.1.2
  - pip:
    - pyradiomics==3.0.1
    - itk==5.2.1.post1
    - git+https://github.com/FabianIsensee/hiddenlayer.git@more_plotted_details#egg=hiddenlayer
    - -e third-party/MONAI
    - -e third-party/HD-BET
    - -e third-party/nnUNet
