subgroups:
  - SHH
  - G3
  - G4
n_folds: 5
folds_file: folds-5.json
protocols:
  - T1
  - T1c
  - T2
segs:
  - AT
sample_size: 448
sample_slices: 16
model: resnet
model_name_or_path: output/pretrain/brats21-16/ep20/state.pth
model_depth: 34
per_device_train_batch_size: 16
recons: false
learning_rate: 1.0e-4
num_train_epochs: 30
aug:
  - flip
  - crop
img_dir: utils/data/datasets/tiantan/stripped
seg_dir: utils/data/datasets/tiantan/origin
output_dir: output/nnunet/bs16-res34-448-AT
cls_factor: 0
seg_factor: 1
num_pretrain_seg: 3
save_strategy: epoch
