subgroups:
  - SHH
  - G3
  - G4
folds_file: folds-3.json
protocols:
  - T1
  - T1c
  - T2
segs:
  - AT
  - CT
sample_size: 224
sample_slices: 16
model: segresnet
per_device_train_batch_size: 8
learning_rate: 1.0e-4
num_train_epochs: 20
aug:
  - flip
img_dir: utils/data/datasets/tiantan/stripped
seg_dir: utils/data/datasets/tiantan/origin
output_dir: output/SHHG34/segresnet/bs8-ep20
cls_factor: 0
seg_factor: 1
vae_factor: 0
