name: stripped
subgroups:
  - WNT
  - SHH
  - G3
  - G4
n_folds: 3
folds_file: folds-3.json
protocols:
  - T1
  - T1c
  - T2
segs:
  - AT
  - CT
sample_size: 224
sample_slices: 16
model: resnet
model_depth: 18
batch_size: 4
recons: false
lr: 1e-4
epochs: 20
patience: 0
aug:
  - flip
img_dir: utils/data/datasets/tiantan/stripped
seg_dir: utils/data/datasets/tiantan/origin
output_dir: output/all/stripped
cls_factor: 0.1
seg_factor: 1
