num_stages: 6
z_strides: [1, 1, 1, 2, 2]
z_kernel_sizes: [1, 1, 1, 3, 3, 3]
swin_window_size: [8, 6, 4]
vit_depths: [2, 2, 18, 2]
vit_num_heads: [3, 6, 12, 24]
feature_channels: [24, 48, 96, 192, 384, 768]
pad_crop_size: [512, 512, 24]
#sample_size: 192
#sample_slices: 16
sample_shape: [256, 192, 16]
input_modalities:
  - T1
  - T1C
  - T2
seg_classes:
  - ST
  - AT
  - CT
spacing: [0.46875, 0.46875, -1]
learning_rate: 1e-4
train_batch_size: 2
eval_batch_size: 2
num_crop_samples: 4
num_train_epochs: 300
warmup_epochs: 10
num_seg_heads: 4
flip_p: 0.5
rotate_p: 0
include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
crop_pos: 1
squared_dice: true
