num_stages: 6
z_strides: [1, 1, 1, 2, 2]
swin_window_size: [6, 6, 6]
vit_depths: [2, 2, 6, 2]
vit_num_heads: [3, 6, 12, 24]
feature_channels: [16, 24, 48, 96, 192, 384]
pad_crop_size: [512, 512, 24]
sample_size: 192
sample_slices: 24
input_modalities:
  - T1
  - T2
seg_classes:
  - ST
  - AT
seg_weights: [0, 1]
spacing: [0.46875, 0.46875, -1]
learning_rate: 1e-5
train_batch_size: 8
num_train_epochs: 100
warmup_epochs: 10
num_seg_heads: 3
flip_p: 0.5
rotate_p: 0
include_background: true
#dice_nr: 1e-5
#dice_dr: 1e-5
#crop_pos: 1
#squared_dice: true
output_dir: output/T1+T2
pool_shape: [2, 2, 2]
seg_pred_dir: output/T1+T2/predict-42+233/sw0.8
cls_weights: [1, 0.8, 0.8, 0.5]
th: 0.4
