model: ../model/unet.yaml
trainer:
  max_steps: 150000
optimization:
- optimizer:
    class_path: torch.optim.SGD
    init_args:
      lr: 5e-3
      weight_decay: 1e-4
      momentum: 0.99
      nesterov: true
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_initial: ${trainer.max_steps}
        t_in_epochs: false
