model: ../model/unet.yaml
optimization:
- optimizer:
    class_path: torch.optim.SGD
    init_args:
      lr: 1e-2
      weight_decay: 3e-5
      momentum: 0.99
      nesterov: true
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_initial: 250000  # TODO: fix this
        t_in_epochs: false
