subgroups:
  - SHH
  - G3
  - G4
n_folds: 3
folds_file: folds-3.json
protocols:
  - T1
  - T1c
  - T2
segs:
  - AT
sample_size: 224
sample_slices: 16
model: resnet
model_depth: 34
per_device_train_batch_size: 8
recons: false
learning_rate: 1e-4
num_train_epochs: 50
aug:
  - flip
#  - noise
#  - blur
img_dir: utils/data/datasets/tiantan/preprocessed
seg_dir: utils/data/datasets/tiantan/preprocessed
output_dir: output/SHHG34/seg/ft-res34-nofg/ep50/bs8-res34-nofg
cls_factor: 0
seg_factor: 1
input_fg_mask: false
seg_inputs: []
model_name_or_path: output/pretrain/res34-nofg/checkpoint-ep50.pth.tar
num_pretrain_seg: 3
