subgroups:
  - SHH
  - G3
  - G4
n_folds: 3
folds_file: folds-3.json
protocols:
  - T1
  - T1c
  - T2
segs:
  - AT
sample_size: 224
sample_slices: 16
model: resnet
model_depth: 34
per_device_train_batch_size: 8
recons: false
learning_rate: 1e-4
num_train_epochs: 200
aug:
  - flip
  - noise
  - blur
img_dir: utils/data/datasets/tiantan/preprocessed
seg_dir: utils/data/datasets/tiantan/preprocessed
output_dir: output/SHHG34/cls+seg/bs8-res34-voxel
cls_factor: 0.1
seg_factor: 1
input_fg_mask: true
seg_inputs: []
