sample_size: 224
sample_slices: 16
model: resnet
model_depth: 34
per_device_train_batch_size: 25
learning_rate: 1e-4
num_train_epochs: 50
aug:
  - flip
  - crop
  - noise
output_dir: output/pretrain/res34-noise-nofg
input_fg_mask: false
