_base:
  - _default.yaml

do_train: true
max_steps: 2000
# backbone_optim:
#   lr: 5e-5
#   weight_decay: 1e
optimizer:
  lr: 1e-4
  weight_decay: 1e-2
scheduler:
  name: multistep
  frequency: 100
  kwargs:
    warmup_t: 500
    decay_t: [1500]
    decay_rate: 0.1
