_base:
  - _default.yaml
  - scheduler: ${luolib.conf_root:}/scheduler/_step.yaml
fold_ids: [3]

max_steps: 700
backbone_optim:
  lr: 1e-5
  weight_decay: 0
optimizer:
  lr: 5e-5
scheduler:
  name: multistep
  frequency: 100
  kwargs:
    warmup_t: 300
    decay_t: [400]
    decay_rate: 0.1
