setting:
  normalize: true
  normalizeScale: 100
  binWidth: 10
  label: 1
  interpolator: 'sitkBSpline' # This is an enumerated value, here None is not allowed
  resampledPixelSpacing: [1,1,1] # This disables resampling, as it is interpreted as None, to enable it, specify spacing in x, y, z as [x, y, z]
  weightingNorm: # If no value is specified, it is interpreted as None
  geometryTolerance: 1e-2
  correctMask: True
imageType:
  Original: {} # for dictionaries/mappings, None values are not allowed, '{}' is interpreted as an empty dictionary
  LoG: {'sigma': [5,3,1]}
  Wavelet: {}
featureClass:
  shape: ['VoxelVolume',
  'MeshVolume',
  'SurfaceArea',
  'SurfaceVolumeRatio',
  'Sphericity',
  'SphericalDisproportion',
  'Maximum3DDiameter',
  'Maximum2DDiameterSlice',
  'Maximum2DDiameterColumn',
  'Maximum2DDiameterRow',
  'Elongation',
  'Flatness'] # Only enable these shape descriptors (disables redundant Compactness 1 and Compactness 2)
  firstorder: [] # specifying an empty list has the same effect as specifying nothing.
  glcm: # for lists none values are allowed, in this case, all features are enabled
  glrlm:
  glszm:
